version: "3.7"

services:
  manager:
    container_name: goldenreports-manager
    image: goldenreports/manager
    build:
      context: ./GoldenReports.UI/manager
    ports:
      - 80:80
    env_file: .env
    depends_on:
      - api

  api:
    container_name: goldenreports-api
    image: goldenreports/api
    build:
      dockerfile: ./GoldenReports.API/Dockerfile
      context: .
    ports:
      - 5001:80
    env_file: .env
    depends_on:
      - postgres

  postgres:
    container_name: goldenreports-postgres
    image: postgres:13-alpine
    ports:
      - 5433:5432
    env_file: .env
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_connections=500"
    volumes:
      - goldenreports_postgres_data:/var/lib/postgresql/data/

volumes:
  goldenreports_postgres_data:
    driver: local

