version: "3.7"

services:
  golden-reports-ui:
    container_name: goldenreports-ui
    image: goldenreports/web-ui
    build:
      dockerfile: ./GoldenReports.WebUI/Dockerfile
      context: .
    ports:
      - 80:80
      - 443:443
    env_file: .env
    depends_on:
      - query-engine

  query-engine:
    container_name: goldenreports-query
    image: goldenreports/query-engine
    build:
      dockerfile: ./GoldenReports.QueryEngine/Dockerfile
      context: .
    ports:
      - 5001:80
    env_file: .env
    depends_on:
      - postgres

  postgres:
    container_name: goldenreports-db
    image: postgres:15-alpine
    ports:
      - 5433:5432
    env_file: .env
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_connections=500"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
    driver: local
  

