name: Application Layer CI

on:
  pull_request:
    branches:
      - 'main'
      - 'dev'
    paths:
      - 'GoldenReports.Application/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3