name: Golden Reports CI/CD

on:
  workflow_dispatch:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write
      issues: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build
        if: github.event_name == 'pull_request'
        run: dotnet build GoldenReports.sln -c Release
      - name: Install Semantic release
        if: github.event_name == 'push'
        run: npm i -g semantic-release @semantic-release/exec
      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
          OUTPUT_DIRECTORY: ${{ github.workspace }}/output
          NUGET_REGISTRY_URL: "https://nuget.pkg.github.com/golden-reports/index.json"
          NUGET_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
          DOCKER_REGISTRY_URL: "ghcr.io/golden-reports"
        run: npx semantic-release
          