name: Golden Reports CI/CD

on:
  workflow_dispatch:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']

env:
  PROJECT_PATH: 'GoldenReports.Domain/GoldenReports.Domain.csproj'
  OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_REGISTRY_URL: ${{ secrets.NUGET_REGISTRY_URL }}
  NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
  DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build
        if: github.event_name == 'pull_request'
        run: dotnet build GoldenReports.sln -c Release
      - name: Install Semantic release
        run: npm i -g semantic-release @semantic-release/exec
      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
        run: npx semantic-release
          