name: Domain Layer CD

on:
  push:
    branches:
      - 'main'
      - 'dev'
    paths:
      - 'GoldenReports.Domain/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3